import { type ReactElement, useEffect, useMemo, useState } from 'react'
import './ReportsPage.css'
import OLMap from '../../components/Map/Map'
import demoComplaints from './demo-complaints.json'
import { apiFetch } from '../../lib/api'

type Report = { id:string; title:string; description?:string; category?:string; subcategory?:string; status?:string; priority?:string; department?:{id:number;name:string}; location?:{latitude:number;longitude:number;address?:string}; image_url?:string; voice_note_url?:string; reported_by?:{id?:string;name?:string;phone?:string}; created_at?:string; updated_at?:string }
type Action = 'assign' | 'resolve' | 'reject' | null
type ApiDepartment = { id: number; name?: string; department_name?: string }
const label = (value?: string) => value ? value.replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase()) : 'Unassigned'

const ReportsPage = (): ReactElement => {
  const [reports, setReports] = useState<Report[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const [statusFilter, setStatusFilter] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [priorityFilter, setPriorityFilter] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0)
  const [sortField, setSortField] = useState<'created_at'|'category'|'priority'>('created_at'); const [sortDir, setSortDir] = useState<'asc'|'desc'>('desc'); const [selected, setSelected] = useState<Report | null>(null); const [mapReport, setMapReport] = useState<Report | null>(null)
  const [actionReport, setActionReport] = useState<Report | null>(null); const [action, setAction] = useState<Action>(null); const [actionValue, setActionValue] = useState(''); const [actionLoading, setActionLoading] = useState(false); const [openMenu, setOpenMenu] = useState<string | null>(null)
  const [departments, setDepartments] = useState<Array<{id:number;name:string}>>([])

  const fetchReports = async () => { setLoading(true); setError(null); try { const params = new URLSearchParams({ page:String(page), limit:'20' }); if(statusFilter)params.set('status',statusFilter);if(categoryFilter)params.set('category',categoryFilter);if(priorityFilter)params.set('priority',priorityFilter); const res=await apiFetch(`/admin/issues?${params}`); if(!res.ok)throw new Error('Unable to load reports. Check the CivicOps API connection.'); const data=(await res.json()).data || {}; setReports(data.issues || []); setTotal(data.total || (data.issues || []).length) } catch(err) { setError(err instanceof Error ? err.message : 'Unable to load reports.'); setReports([]) } finally { setLoading(false) } }
  // fetchReports deliberately tracks the filter state; including its recreated function would retrigger every render.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { fetchReports() }, [statusFilter, categoryFilter, priorityFilter, page])
  useEffect(() => { apiFetch('/admin/departments').then(res => res.ok ? res.json() : null).then((json: { data?: { departments?: ApiDepartment[] } | ApiDepartment[] } | null) => { const data = json?.data; const list: ApiDepartment[] = Array.isArray(data) ? data : data?.departments || []; setDepartments(list.map(department => ({id:department.id,name:department.name || department.department_name || 'Unnamed department'}))) }).catch(() => setDepartments([{id:1,name:'Public Works'},{id:2,name:'Solid Waste Management'},{id:3,name:'Water Supply'}])) }, [])
  const categories = useMemo(() => [...new Set(reports.map(r => r.category).filter(Boolean) as string[])], [reports])
  const filtered = useMemo(() => { const q=query.trim().toLowerCase(); return [...reports].filter(r => !q || [r.title,r.description,r.reported_by?.name,r.id].some(value => value?.toLowerCase().includes(q))).sort((a,b) => { const result=String(a[sortField] || '').localeCompare(String(b[sortField] || '')); return sortDir==='asc'?result:-result }) }, [reports,query,sortField,sortDir])
  const toggleSort = (field: typeof sortField) => { if(field===sortField)setSortDir(value => value==='asc'?'desc':'asc'); else {setSortField(field);setSortDir('asc')} }
  const clearFilters = () => { setStatusFilter('');setCategoryFilter('');setPriorityFilter('');setQuery('');setPage(1) }
  const useDemo = () => { const list=demoComplaints as unknown as Report[]; setReports(list);setTotal(list.length);setError(null) }
  const startAction = (report:Report, next:Action) => { setOpenMenu(null);setActionReport(report);setAction(next);setActionValue('') }
  const performAction = async () => { if(!actionReport || !action) return; const body = action==='assign' ? {department_id:Number(actionValue)} : action==='resolve' ? {status:'resolved',resolution:actionValue} : {status:'rejected',reject_reason:actionValue}; setActionLoading(true); try { const response=await apiFetch(`/admin/issues/${actionReport.id}`, {method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); if(!response.ok)throw new Error('The update could not be saved.'); setReports(old => old.map(report => report.id!==actionReport.id ? report : {...report,status: action==='resolve'?'resolved':action==='reject'?'rejected':report.status, department:action==='assign'?departments.find(d=>d.id===Number(actionValue)):report.department})); setAction(null);setActionReport(null) } catch(err) { setError(err instanceof Error ? err.message:'The update could not be saved.') } finally {setActionLoading(false)} }
  const statusClass = (status?:string) => `report-status ${status || 'reported'}`
  const priorityClass = (priority?:string) => `report-priority ${priority || 'unassigned'}`
  return <div className="reports-page">
    <section className="reports-top"><div><h2>Report management</h2><p>Review citizen requests and keep every case moving to resolution.</p></div><div className="reports-top-actions"><button className="report-button secondary" onClick={useDemo}>Use demo data</button><button className="report-button primary" onClick={fetchReports}>↻ Refresh reports</button></div></section>
    <section className="report-summary"><div><span>Visible reports</span><strong>{loading ? '—' : filtered.length}</strong></div><div><span>Awaiting assignment</span><strong>{reports.filter(r=>!r.department).length}</strong></div><div><span>In progress</span><strong>{reports.filter(r=>r.status==='in_progress').length}</strong></div><div><span>Resolved</span><strong>{reports.filter(r=>r.status==='resolved').length}</strong></div></section>
    <section className="reports-workspace">
      <aside className="report-filters"><div className="filter-heading"><div><h3>Filters</h3><p>Narrow the work queue</p></div><button onClick={clearFilters} disabled={!statusFilter&&!categoryFilter&&!priorityFilter&&!query}>Clear</button></div><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ID, title or reporter" /></label><label>Status<select value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="reported">Reported</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="rejected">Rejected</option></select></label><label>Priority<select value={priorityFilter} onChange={e=>{setPriorityFilter(e.target.value);setPage(1)}}><option value="">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Category<select value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);setPage(1)}}><option value="">All categories</option>{categories.map(category=><option key={category}>{category}</option>)}</select></label></aside>
      <div className="report-table-card"><div className="table-toolbar"><div><h3>All reports</h3><p>{total || filtered.length} reports in this workspace</p></div><span className="table-status-dot">Live data</span></div>{error && <div className="report-error"><span>!</span>{error}<button onClick={fetchReports}>Try again</button></div>}{loading ? <div className="report-loading"><i /> Loading reports…</div> : filtered.length===0 ? <div className="report-empty"><div>⌕</div><h3>No reports found</h3><p>Try changing your filters, or load the demo dataset.</p><button className="report-button secondary" onClick={clearFilters}>Clear filters</button></div> : <div className="report-table-wrap"><table className="report-table"><thead><tr><th>Report</th><th><button onClick={()=>toggleSort('category')}>Category {sortField==='category' && (sortDir==='asc'?'↑':'↓')}</button></th><th><button onClick={()=>toggleSort('priority')}>Priority {sortField==='priority' && (sortDir==='asc'?'↑':'↓')}</button></th><th>Status</th><th>Assignment</th><th><button onClick={()=>toggleSort('created_at')}>Reported {sortField==='created_at' && (sortDir==='asc'?'↑':'↓')}</button></th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map(report=><tr key={report.id}><td><button className="report-name" onClick={()=>setSelected(report)}>{report.title}<small>#{report.id.slice(-8)} · {report.reported_by?.name || 'Anonymous resident'}</small></button></td><td><span className="category-cell">{label(report.category)}</span></td><td><span className={priorityClass(report.priority)}>{label(report.priority)}</span></td><td><span className={statusClass(report.status)}><i />{label(report.status)}</span></td><td><span className="assignment-cell">{report.department?.name || 'Unassigned'}</span></td><td><time>{report.created_at ? new Date(report.created_at).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}) : '—'}</time></td><td className="action-cell"><button className="row-menu-button" aria-label={`Actions for ${report.title}`} onClick={()=>setOpenMenu(openMenu===report.id?null:report.id)}>•••</button>{openMenu===report.id && <div className="row-menu"><button onClick={()=>{setSelected(report);setOpenMenu(null)}}>View details</button><button onClick={()=>startAction(report,'assign')}>Assign department</button><button onClick={()=>setMapReport(report)}>View on map</button><hr /><button onClick={()=>startAction(report,'resolve')} className="menu-success">Mark resolved</button><button onClick={()=>startAction(report,'reject')} className="menu-danger">Reject report</button></div>}</td></tr>)}</tbody></table></div>}<div className="report-pagination"><span>Page {page} · Showing {filtered.length} of {total || filtered.length}</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={filtered.length<20} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></div>
    </section>
    {selected && <div className="report-modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="report-modal detail-modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close">×</button><header><span className={statusClass(selected.status)}><i />{label(selected.status)}</span><h2>{selected.title}</h2><p>#{selected.id} · {label(selected.category)} {selected.subcategory && ` / ${label(selected.subcategory)}`}</p></header><div className="detail-content"><div className="detail-main"><h3>Report details</h3><p>{selected.description || 'No additional description was provided by the resident.'}</p>{selected.image_url && <img src={selected.image_url} alt="Reported issue" />}{selected.voice_note_url && <audio controls src={selected.voice_note_url} />}</div><aside className="detail-meta"><div><span>Priority</span><b className={priorityClass(selected.priority)}>{label(selected.priority)}</b></div><div><span>Department</span><strong>{selected.department?.name || 'Unassigned'}</strong></div><div><span>Reported by</span><strong>{selected.reported_by?.name || 'Anonymous resident'}</strong><small>{selected.reported_by?.phone}</small></div><div><span>Location</span><strong>{selected.location?.address || 'Location unavailable'}</strong></div></aside></div><footer><button className="report-button secondary" onClick={()=>setMapReport(selected)}>View on map</button><button className="report-button secondary" onClick={()=>startAction(selected,'assign')}>Assign</button><button className="report-button primary" onClick={()=>startAction(selected,'resolve')}>Mark resolved</button></footer></section></div>}
    {mapReport && <div className="report-modal-backdrop" onMouseDown={()=>setMapReport(null)}><section className="report-modal map-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setMapReport(null)} aria-label="Close">×</button><h2>{mapReport.title}</h2><p>{mapReport.location?.address || 'Reported location'}</p>{mapReport.location ? <OLMap reports={[{id:mapReport.id,title:mapReport.title,longitude:mapReport.location.longitude,latitude:mapReport.location.latitude}]} /> : <div className="map-empty">This report has no location coordinates.</div>}</section></div>}
    {action && actionReport && <div className="report-modal-backdrop"><section className="report-modal action-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setAction(null)} aria-label="Close">×</button><h2>{action==='assign'?'Assign department':action==='resolve'?'Resolve report':'Reject report'}</h2><p>{action==='assign'?`Choose the responsible team for “${actionReport.title}”.`:action==='resolve'?'Add a brief resolution note for the audit trail.':'Add a reason before rejecting this citizen report.'}</p>{action==='assign'?<select value={actionValue} onChange={e=>setActionValue(e.target.value)}><option value="">Select a department</option>{departments.map(dept=><option key={dept.id} value={dept.id}>{dept.name}</option>)}</select>:<textarea autoFocus rows={4} value={actionValue} onChange={e=>setActionValue(e.target.value)} placeholder={action==='resolve'?'Describe the resolution':'Explain the reason for rejection'} />}<footer><button className="report-button secondary" onClick={()=>setAction(null)}>Cancel</button><button className={`report-button ${action==='reject'?'danger':'primary'}`} disabled={!actionValue.trim()||actionLoading} onClick={performAction}>{actionLoading?'Saving…':action==='assign'?'Assign department':action==='resolve'?'Mark resolved':'Reject report'}</button></footer></section></div>}
  </div>
}
export default ReportsPage
