import { type ReactElement, useMemo, useState } from 'react'
import './FieldStaffPage.css'

type TaskStatus = 'In progress' | 'Awaiting verification' | 'Completed'
type Task = { id:string; complaint:string; department:string; location:string; status:TaskStatus; progress:number; due:string; workers:{name:string;initials:string}[]; contractor:{name:string;id:string;company:string;rating:number;completed:number}; images:{url:string;caption:string}[]; note:string }
const tasks: Task[] = [
  {id:'CIV-2025-1842',complaint:'Pothole repair on Main Street',department:'Public Works Department',location:'Main Street, Ward 07',status:'In progress',progress:65,due:'Today, 4:30 PM',workers:[{name:'Rajesh Kumar',initials:'RK'},{name:'Imran Shaikh',initials:'IS'},{name:'Amit Verma',initials:'AV'}],contractor:{name:'Suresh Patil',id:'CON-PWD-0194',company:'Patil Roadworks Pvt. Ltd.',rating:4.7,completed:128},images:[{url:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80',caption:'Surface preparation — 10:24 AM'},{url:'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=80',caption:'Repair crew on site — 11:10 AM'}],note:'Base layer repaired; final asphalt layer is in progress.'},
  {id:'CIV-2025-1837',complaint:'Overflowing waste bin near market',department:'Solid Waste Management',location:'Central Market, Ward 12',status:'Awaiting verification',progress:100,due:'Completed today',workers:[{name:'Neha Singh',initials:'NS'},{name:'Karan Joshi',initials:'KJ'}],contractor:{name:'Meera Enterprises',id:'CON-SWM-0082',company:'Meera Environmental Services',rating:4.5,completed:86},images:[{url:'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=900&q=80',caption:'Bin cleared and area cleaned — 09:42 AM'},{url:'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=900&q=80',caption:'Replacement bin installed — 09:50 AM'}],note:'Completion photos submitted by the supervisor. Awaiting department review.'},
  {id:'CIV-2025-1819',complaint:'Streetlight outage at community park',department:'Streetlighting Department',location:'Shivaji Park, Ward 03',status:'Completed',progress:100,due:'Completed 14 Aug',workers:[{name:'Sanjay Rao',initials:'SR'},{name:'Vikram Das',initials:'VD'}],contractor:{name:'Suresh Patil',id:'CON-LGT-0111',company:'Urban Light Solutions',rating:4.8,completed:204},images:[{url:'https://images.unsplash.com/photo-1519608487953-e999c86e7450?auto=format&fit=crop&w=900&q=80',caption:'New fixture installed — 07:35 PM'},{url:'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=80',caption:'Streetlight tested after repair — 07:48 PM'}],note:'Faulty driver replaced and illumination test passed.'},
  {id:'CIV-2025-1804',complaint:'Water leakage from public pipeline',department:'Water Supply Department',location:'Station Road, Ward 16',status:'In progress',progress:35,due:'Tomorrow, 12:00 PM',workers:[{name:'Farhan Ali',initials:'FA'},{name:'Deepak Yadav',initials:'DY'},{name:'Ravi Jadhav',initials:'RJ'},{name:'Nilesh Pawar',initials:'NP'}],contractor:{name:'AquaLine Contractors',id:'CON-WTR-0047',company:'AquaLine Infrastructure',rating:4.3,completed:67},images:[{url:'https://images.unsplash.com/photo-1581093458791-9d42e3c5b17d?auto=format&fit=crop&w=900&q=80',caption:'Leak investigation and isolation — 01:05 PM'},{url:'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=80',caption:'Pipe replacement work underway — 02:18 PM'}],note:'Water line isolated. Replacement fitting has been requested.'},
]
const allWorkers = new Set(tasks.flatMap(task=>task.workers.map(worker=>worker.name))).size
const stars=(rating:number)=>`${rating.toFixed(1)} ★`

const FieldStaffPage = (): ReactElement => {
  const [query,setQuery] = useState(''); const [status,setStatus] = useState('All'); const [selected,setSelected] = useState<Task | null>(null); const [preview,setPreview] = useState<{url:string;caption:string}|null>(null)
  const filtered=useMemo(()=>tasks.filter(task=>(status==='All'||task.status===status)&&(!query.trim()||[task.id,task.complaint,task.department,task.contractor.name].join(' ').toLowerCase().includes(query.toLowerCase().trim()))),[query,status])
  return <div className="field-staff-page">
    <section className="field-staff-top"><div><h2>Field workforce</h2><p>Track assigned work, completion evidence and contractor performance.</p></div><div className="field-live"><i /> Field updates active</div></section>
    <section className="field-summary"><article><span>Active work orders</span><strong>{tasks.filter(task=>task.status==='In progress').length}</strong><small>Tasks being completed on site</small></article><article><span>Workers deployed</span><strong>{allWorkers}</strong><small>Across {tasks.filter(task=>task.status!=='Completed').length} active teams</small></article><article><span>Awaiting verification</span><strong>{tasks.filter(task=>task.status==='Awaiting verification').length}</strong><small>Field evidence needs review</small></article><article><span>Average contractor rating</span><strong>{(tasks.reduce((sum,task)=>sum+task.contractor.rating,0)/tasks.length).toFixed(1)} ★</strong><small>Public feedback across assigned contractors</small></article></section>
    <section className="field-board"><div className="field-board-head"><div><h3>Assigned task board</h3><p>Each work order is linked to its original citizen complaint.</p></div><div className="field-controls"><input placeholder="Search complaint, ID or contractor" value={query} onChange={event=>setQuery(event.target.value)} /><select value={status} onChange={event=>setStatus(event.target.value)}><option>All</option><option>In progress</option><option>Awaiting verification</option><option>Completed</option></select></div></div><div className="task-table-wrap"><table className="task-table"><thead><tr><th>Work order / complaint</th><th>Department</th><th>Workforce</th><th>Progress</th><th>Evidence</th><th>Due / status</th><th /></tr></thead><tbody>{filtered.map(task=><tr key={task.id}><td><strong>{task.complaint}</strong><small>{task.id} · {task.location}</small></td><td>{task.department}</td><td><div className="worker-stack">{task.workers.slice(0,3).map(worker=><span key={worker.name} title={worker.name}>{worker.initials}</span>)}{task.workers.length>3&&<b>+{task.workers.length-3}</b>}</div><small>{task.workers.length} workers</small></td><td><div className="progress-cell"><div><i style={{width:`${task.progress}%`}} /></div><span>{task.progress}%</span></div></td><td><div className="evidence-stack">{task.images.map(image=><button key={image.url} onClick={()=>setPreview(image)}><img src={image.url} alt={image.caption}/></button>)}</div></td><td><span className={`task-status ${task.status.toLowerCase().replaceAll(' ','-')}`}>{task.status}</span><small>{task.due}</small></td><td><button className="task-view" onClick={()=>setSelected(task)}>View task</button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="field-empty">No assigned field tasks match the current filters.</div>}</section>
    <section className="field-evidence-section"><div className="evidence-heading"><div><h3>Latest fixing reports</h3><p>Photo evidence uploaded by field staff for supervisor review.</p></div><span>Click an image to enlarge</span></div><div className="field-gallery">{tasks.flatMap(task=>task.images.map(image=>({...image,task}))).slice(0,6).map(item=><button className="field-photo" key={`${item.task.id}-${item.url}`} onClick={()=>setPreview(item)}><img src={item.url} alt={item.caption}/><span><strong>{item.task.id}</strong>{item.caption}</span></button>)}</div></section>
    {selected&&<div className="field-modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="field-task-modal" onMouseDown={event=>event.stopPropagation()} role="dialog" aria-modal="true"><button className="field-modal-close" onClick={()=>setSelected(null)}>×</button><header><span className={`task-status ${selected.status.toLowerCase().replaceAll(' ','-')}`}>{selected.status}</span><h2>{selected.complaint}</h2><p>{selected.id} · {selected.location}</p></header><div className="field-detail-grid"><div><h3>Work progress</h3><div className="large-progress"><i style={{width:`${selected.progress}%`}} /></div><strong>{selected.progress}% complete</strong><p>{selected.note}</p><h3>Uploaded fixing evidence</h3><div className="detail-gallery">{selected.images.map(image=><button key={image.url} onClick={()=>setPreview(image)}><img src={image.url} alt={image.caption}/><span>{image.caption}</span></button>)}</div></div><aside><h3>Field team</h3>{selected.workers.map(worker=><div className="detail-worker" key={worker.name}><span>{worker.initials}</span>{worker.name}</div>)}<h3>Contractor</h3><div className="contractor-card"><span className="contractor-logo">{selected.contractor.name.slice(0,2).toUpperCase()}</span><strong>{selected.contractor.name}</strong><small>{selected.contractor.company}</small><dl><div><dt>Contractor ID</dt><dd>{selected.contractor.id}</dd></div><div><dt>Past tasks done</dt><dd>{selected.contractor.completed}</dd></div><div><dt>Public rating</dt><dd>{stars(selected.contractor.rating)}</dd></div></dl></div></aside></div></section></div>}
    {preview&&<div className="field-modal-backdrop image-backdrop" onMouseDown={()=>setPreview(null)}><figure className="image-preview" onMouseDown={event=>event.stopPropagation()}><button onClick={()=>setPreview(null)}>×</button><img src={preview.url} alt={preview.caption}/><figcaption>{preview.caption}</figcaption></figure></div>}
  </div>
}
export default FieldStaffPage
